January:
  - '/\d{4}-01-\d{2}/'
February:
  - '/\d{4}-02-\d{2}/'
March:
  - '/\d{4}-03-\d{2}/'
April:
  - '/\d{4}-04-\d{2}/'
May:
  - '/\d{4}-05-\d{2}/'
June:
  - '/\d{4}-06-\d{2}/'
July:
  - '/\d{4}-07-\d{2}/'
August:
  - '/\d{4}-08-\d{2}/'
September:
  - '/\d{4}-09-\d{2}/'
October:
  - '/\d{4}-10-\d{2}/'
November:
  - '/\d{4}-11-\d{2}/'
December:
  - '/\d{4}-12-\d{2}/'
