name: Bug Report
description: Report a bug or issue with the Open Source Friday project
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: ["LadyKerr", "AndreaGriffiths11", "KevinCrosby"]

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        #### :bug: Thank you for taking the time to report a bug! Please provide detailed information to help us understand and fix the issue. :bug:

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe the bug you encountered..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: "What should have happened instead?"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: "What actually happened?"
    validations:
      required: true

  - type: dropdown
    id: bug_area
    attributes:
      label: Area Affected
      description: Which part of the Open Source Friday project is affected?
      options:
        - Website/Documentation
        - Live Stream Process
        - GitHub Workflows/Automation
        - Guest Invitation Process
        - Issue Templates
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide relevant environment details
      placeholder: |
        - Browser: [e.g. Chrome, Firefox, Safari]
        - Operating System: [e.g. Windows, macOS, Linux]
        - Device: [e.g. Desktop, Mobile, Tablet]
        - Any other relevant technical details
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: If applicable, add screenshots or error logs to help explain your problem
      placeholder: "Paste screenshots or logs here..."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "Any additional information that might be helpful..."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have provided all the requested information above
          required: true