name: Debug Issue Handle Extraction

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to debug'
        required: true
        type: number

jobs:
  debug-handle:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub handle extraction
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = ${{ github.event.inputs.issue_number }};
            
            try {
              const issue = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              
              const issueBody = issue.data.body;
              console.log('=== ISSUE BODY ===');
              console.log(issueBody);
              console.log('=== END ISSUE BODY ===');
              
              // Test multiple patterns
              const patterns = [
                /### GitHub Handle\s*\n\s*@([a-zA-Z0-9-]+)/,
                /GitHub Handle\s*\n\s*@([a-zA-Z0-9-]+)/,
                /@[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38}/gi
              ];
              
              console.log('\n=== PATTERN MATCHING RESULTS ===');
              for (let i = 0; i < patterns.length; i++) {
                const pattern = patterns[i];
                const match = pattern.exec(issueBody);
                console.log(`Pattern ${i + 1}:`, pattern);
                console.log(`Match result:`, match);
                if (match) {
                  const handle = match[1] || match[0].substring(1);
                  console.log(`Extracted handle:`, handle);
                }
                console.log('---');
              }
              
            } catch (error) {
              console.error('Error fetching issue:', error);
            }