name: Notify Approved Guests

on:
  issues:
    types: [labeled]

jobs:
  notify-approved-guest:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'approved'
    steps:
      - name: Comment on approved issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueBody = context.payload.issue.body;
            console.log('Issue body:', issueBody);
            
            // Try multiple patterns to find GitHub handle
            const patterns = [
              /### GitHub Handle\s*\n\s*@([a-zA-Z0-9-]+)/,
              /GitHub Handle\s*\n\s*@([a-zA-Z0-9-]+)/,
              /@[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38}/gi
            ];
            
            let githubHandle = null;
            
            for (const pattern of patterns) {
              const match = pattern.exec(issueBody);
              if (match) {
                githubHandle = match[1] || match[0].substring(1);
                console.log('Found handle with pattern:', pattern, 'Result:', githubHandle);
                break;
              }
            }
            
            if (githubHandle) {
              // Sanitize the GitHub handle
              const sanitizedHandle = githubHandle.replace(/[^a-zA-Z0-9-]/g, '');
              
              // Validate handle format
              if (sanitizedHandle.length >= 1 && sanitizedHandle.length <= 39 && 
                  !sanitizedHandle.startsWith('-') && !sanitizedHandle.endsWith('-') && 
                  sanitizedHandle.match(/^[a-zA-Z0-9-]+$/)) {
                
                console.log('Creating comment for handle:', sanitizedHandle);
                const issueComment = {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: 'Hey @' + sanitizedHandle + ' thank you for submitting your project! Looks super interesting! ✨\n\nPlease select a date from this calendar: https://gh.io/osf-booking\n\nDo let me know in this issue what date you selected for the stream! 📅'
                };
                
                try {
                  const result = await github.rest.issues.createComment(issueComment);
                  console.log('Comment created successfully:', result.data.id);
                } catch (error) {
                  console.error('Failed to create comment:', error);
                  throw error;
                }
              } else {
                console.log('Handle validation failed for:', sanitizedHandle);
              }
            } else {
              console.log('No GitHub handle found in issue body');
            }